apiVersion: apps/v1

kind: ReplicaSet

metadata:
  name: go-api
  labels:
    app: go-api

spec:
  selector:
    matchLabels:
      app: go-api
  replicas: 5
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
        - name: go-api
          image: nichollasf/kubernetes-go-server:latest
