apiVersion: v1

kind: Service

metadata:
  name: go-api-service

spec:
  selector:
    app: go-api
  type: ClusterIP
  ports:
    - name: go-api
      port: 8484
      targetPort: 8282
      protocol: TCP
